export const TOOLS = {
  NO_SELECTED_TOOL: "NO_SELECTED_TOOL",
  INK: "INK",
  CIRCLE: "CIRCLE",
  SQUARE: "SQUARE",
  ARROW: "ARROW",
  MARKER: "MARKER",
  UNDERLINE: "UNDERLINE",
  CROSSLINE: "CROSSLINE",
  TEXT_BOX: "TEXT_BOX",
  IMAGE: "IMAGE",
  COMMENT: "COMMENT",
  REPLY: "REPLY",

  // unused tools 🤷
  LEAF: "LEAF",
  STAMP: "STAMP",
  BOOKMARK: "BOOKMARK",
  AUDIO: "AUDIO",
};

export const ANNOTATION_TYPES = {
  INK: "InkAnnotation",
  CIRCLE: "CircleAnnotation",
  SQUARE: "SquareAnnotation",
  ARROW: "ArrowAnnotation",
  HIGHLIGHT: "HighlightAnnotation",
  TEXT_BOX: "TextBoxAnnotation",
  IMAGE: "ImageAnnotation",
  COMMENT: "CommentAnnotation",
  REPLY: "ReplyAnnotation",
};

export const ANNOTATION_WEIGHT = [
  ANNOTATION_TYPES.TEXT_BOX,
  ANNOTATION_TYPES.INK,
  ANNOTATION_TYPES.ARROW,
  ANNOTATION_TYPES.CIRCLE,
  ANNOTATION_TYPES.SQUARE,
  ANNOTATION_TYPES.COMMENT,
  ANNOTATION_TYPES.IMAGE,
  ANNOTATION_TYPES.HIGHLIGHT,
];

export const HighlightKind = {
  MARKER: "MARKER",
  UNDERLINE: "UNDERLINE",
  CROSSLINE: "CROSSLINE",
};

export const PERMISSIONS = {
  MANAGE_ANNOTATION: "MANAGE_ANNOTATION",
  DELETE_FOREIGN_ANNOTATION: "DELETE_FOREIGN_ANNOTATION",
  MANAGE_OWN_COMMENT: "MANAGE_OWN_COMMENT",
  DELETE_FOREIGN_COMMENT: "DELETE_FOREIGN_COMMENT",
  SHARE_WORKSPACE: "SHARE_WORKSPACE",
  PUBLISH_WORKSPACE: "PUBLISH_WORKSPACE",
  RENAME_WORKSPACE: "RENAME_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  ARCHIVE_WORKSPACE: "ARCHIVE_WORKSPACE",
  DUPLICATE_WORKSPACE: "DUPLICATE_WORKSPACE",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  RENAME_DOCUMENT: "RENAME_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  COPY_DOCUMENT: "COPY_DOCUMENT",
  DOWNLOAD_SOURCE_DOCUMENT: "DOWNLOAD_SOURCE_DOCUMENT",
  DOWNLOAD_ORIGINAL_DOCUMENT: "DOWNLOAD_ORIGINAL_DOCUMENT",
  DOWNLOAD_ANNOTATED_DOCUMENT: "DOWNLOAD_ANNOTATED_DOCUMENT",
};

export const FONT_FAMILY = {
  SANS_SERIF: "Source Sans Pro",
  SERIF: "Lora",
  MONOSPACE: "Courier Prime",
  SCRIPT: "Cookie",
  FANTASY: "Eagle Lake",
};

export const TEXT_ALIGNMENT = {
  START: "left",
  CENTER: "center",
  END: "right",
};

export const FONT_WEIGHT = {
  W400: "normal",
  W600: "bold",
};
